### PR TITLE
Improvement to Docker container

### PR DESCRIPTION
**Pull request by donbeave**
Hello!

Here is some small improvement.

* Upgraded to Alpine 3.8
* Added ability to enter container with bash or another shell to do some custom stuff
* Added script to build a container
* Removed `dev` dependencies from the container (to minimize it size)

How about build this container automatically with Travis and push it to Docker Hub?

Best regards,
  Alexey Zhokhov.

### CODE REVIEW

**Comment by djrobstep** [comment]
Hey, thanks so much for this pull request. Looks like some good changes. Rather busy at the moment but will give it a proper review as soon as I can!

**Comment by djrobstep** [comment]
Hi there, sorry I've left it so long to review this. 

Docker build looks good, nice and compact.

One question: Could you explain a little more what the use case is for the custom entrypoint script?

**Comment by donbeave** [comment]
I just make it more flexible like other containers. If you have something like this:
```
ENTRYPOINT [ "/usr/bin/migra" ]

CMD ["--help"]
```

and if you try to login to container you will get an error:

```
docker exec -ti 6d1513bfbcf7 /bin/sh
```

because it will run this:
```
/usr/bin/migra /bin/sh
```

So, best practise is do like what `postgres` container did:
https://github.com/docker-library/postgres/blob/064113e0e481a1d0542846b81858e457fde02c90/10/Dockerfile

https://github.com/docker-library/postgres/blob/064113e0e481a1d0542846b81858e457fde02c90/10/docker-entrypoint.sh#L172

```
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["postgres"]
```

when first argument is `postgres` it will pass other arguments to postgres command, if not, it will run arguments directly as a command, so `/bin/sh` will work correctly.

**Comment by djrobstep** [comment]
Makes sense, merging. Thanks so much for contributing this!

**Pull request merged**
