### PR TITLE
Allow for alter of enum vs create / drop when able

### LINKED ISSUE #83: Enum type that has a value added fails to migrate
Repro:

- DB-A and DB-B are identical, and have an Enum type described
- Enum is used as the type for one of the columns in a table
- Alter the enum (add another value) to DB-A

Expectation:

- Upgrade schema has an alter for adding the missing type

Actual:

- Upgrade schema tries (and fails) to drop and re-add the enum

### PR DESCRIPTION
**Pull request by BadPirate**
Issue:  For situations where enum is used as column
type, and another value is added, drop fails.  Alter should
be used when available.

Fixes #83

### CODE REVIEW

**Comment by bricklen** [comment]
Modifying a system catalog (`pg_catalog.pg_enum`) requires superuser privileges, IIRC. If migra is expected to run as a superuser and not as a privileged user, it's probably fine, but if a non-superuser executes the `INSERT INTO pg_enum` command, it should fail. 

"privileged" users, for example, could be the db owner, or the owner of the object being modified, but they are not by default able to modify system-level relations.

Something else to take note of: if the default `search_path` is modified for the user executing the migra changes, any non-schema-qualified objects might result in making changes to an object of the same name in a different schema. For that reason, if a relation like `pg_enum` is intended to be updated, it's probably safer to qualify the relation with the schema prefix.

**Comment by BadPirate** [comment]
Regarding superuser:

Yeah, alter seems less risky, the Insert hack which requires super-user was necessary because alter doesn't (for some reason) work in a transaction, and multiple commands in psql are always treated as a transaction.  I've been using it because my use case has me regularly "expanding" my enums with new values and I needed the transition script to gracefully cope, and while not ideal, was okay with giving super user access to the database to my migration user so that it could "make the call".

Would you be able to suggest any ways to run a particular command outside of the transaction?  It was in my search for that answer that I found the Insert hack.  

Regarding schema name:

Yeah, I hadn't thought to add it, but it should go before the table name, "public"."pg_enum" or whatever right?  Will make that update.

Regarding using alter instead:

Thinking on it, it might be possible to make an option where migra executes the commands rather than just outputting them, thus providing control over transaction, and being able to run alters separate.  It's risky as well in that we could have some alters succeed before one fails and in that case would not be able to rollback...  But probably not the worst thing in the case of expanding enumerations? :/

**Comment by BadPirate** [comment]
@bricklen credit for nits not djrob.  I just wanted to say THE DJ Robstep!??!

**Comment by djrobstep** [comment]
Hello, really appreciate this pull request! Sorry that it's taken so long to get to reviewing it. 

Have been busy but will get to it soon

**Comment by emilbayes** [comment]
I'd much prefer the native alters. Altering tables cannot run in transactions either

**Comment by talsaiag** [comment]
could use this, any updates?

**Comment by BadPirate** [comment]
@talsaiag - You can pull my fork haven't heard an update on whether or not this will merge into main.

**Comment by djrobstep** [comment]
Hey @BadPirate, apologies again that it's taken so long to get to this.

Some thoughts/notes:

- I'm uneasy about going down the path of directly modifying system catalogs, as I don't think this is really in the spirit of the tool.

- I haven't tried this out yet, but I notice that as of PG12, enum alters are now permissible within transactions, at least according to the docs:

> If ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) is executed inside a transaction block, the new value cannot be used until after the transaction has been committed.

vs for versions <=11:

> ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) cannot be executed inside a transaction block.

I don't know what PG versions you're dealing with/are interested in supporting, but perhaps the best way forward is to implement the new alters for version 12 only.  What do you think?

**Comment by BadPirate** [comment]
I've actually changed my app design from homespun Postgres server to Hasura, which means I haven't been using the migra code :)  Commented again because it looks like others had a desire for this change and wanted to point out they could use from fork.  I think the PG12 solution does sound better, so I'm going to close this MR, anyone in the future feel free to pick up from my change or make a better one.

**Pull request closed without merging**
