### PR TITLE
add support for triggers

### PR DESCRIPTION
**Pull request by mshahbazi**

### CODE REVIEW

**Comment by djrobstep** [comment]
Looks good, is it possible you could add one or two tests to confirm it works?

I'm hesitant about pushing out a new feature like this untested.

**Comment by mshahbazi** [comment]
Thanks, 
sure, I will.
yesterday I realized that the __eq__ function always returns false when the pg versions are different (at least for 9.6 and 9.5 in my case). I will fix it and will add a test as well.

**Comment by akeeman** [comment]
It would be awesome if this could be finished!

**Comment by djrobstep** [comment]
@mshahbazi In the interests of speed i've gone ahead and done a release that adds trigger support and a basic test example. If you had any more thorough test fixtures to add, that would be super useful.

**Comment by mshahbazi** [comment]
Thank you so much and sorry for the delay. Actually, I need more time to cope with the __eq__ issue. I will add more tests as soon as I can handle it.

**Comment by mshahbazi** [comment]
managed to handle trigger comparison issue, as well as that of index comparison. hope it helps

**Comment by djrobstep** [comment]
this has now been incorporated, thank you!

**Pull request closed without merging**
